import React from 'react';
import { Layout, Menu, Breadcrumb, Icon } from 'antd';
const { SubMenu } = Menu;
const { Header, Content, Sider } = Layout;
export const LayoutContainer = () => {
    return (React.createElement(Layout, { style: { height: `100%` } },
        React.createElement(Header, null,
            React.createElement(Menu, { theme: "dark", mode: "horizontal", defaultSelectedKeys: ['2'], style: { lineHeight: '64px' } },
                React.createElement(Menu.Item, { key: "1" }, "nav 1"),
                React.createElement(Menu.Item, { key: "2" }, "nav 2"),
                React.createElement(Menu.Item, { key: "3" }, "nav 3"))),
        React.createElement(Layout, null,
            React.createElement(Sider, { width: 200, style: { background: '#fff' } },
                React.createElement(Menu, { mode: "inline", defaultSelectedKeys: ['1'], defaultOpenKeys: ['sub1'], style: { height: '100%', borderRight: 0 } },
                    React.createElement(SubMenu, { key: "sub1", title: React.createElement("span", null,
                            React.createElement(Icon, { type: "user" }),
                            "subnav 1") },
                        React.createElement(Menu.Item, { key: "1" }, "option1"),
                        React.createElement(Menu.Item, { key: "2" }, "option2"),
                        React.createElement(Menu.Item, { key: "3" }, "option3"),
                        React.createElement(Menu.Item, { key: "4" }, "option4")),
                    React.createElement(SubMenu, { key: "sub2", title: React.createElement("span", null,
                            React.createElement(Icon, { type: "laptop" }),
                            "subnav 2") },
                        React.createElement(Menu.Item, { key: "5" }, "option5"),
                        React.createElement(Menu.Item, { key: "6" }, "option6"),
                        React.createElement(Menu.Item, { key: "7" }, "option7"),
                        React.createElement(Menu.Item, { key: "8" }, "option8")),
                    React.createElement(SubMenu, { key: "sub3", title: React.createElement("span", null,
                            React.createElement(Icon, { type: "notification" }),
                            "subnav 3") },
                        React.createElement(Menu.Item, { key: "9" }, "option9"),
                        React.createElement(Menu.Item, { key: "10" }, "option10"),
                        React.createElement(Menu.Item, { key: "11" }, "option11"),
                        React.createElement(Menu.Item, { key: "12" }, "option12")))),
            React.createElement(Layout, { style: { padding: '0 24px 24px' } },
                React.createElement(Breadcrumb, { style: { margin: '16px 0' } },
                    React.createElement(Breadcrumb.Item, null, "Home"),
                    React.createElement(Breadcrumb.Item, null, "List"),
                    React.createElement(Breadcrumb.Item, null, "App")),
                React.createElement(Content, { style: {
                        background: '#fff',
                        padding: 24,
                        margin: 0,
                        minHeight: 280,
                    } }, "Content")))));
};
